### ISSUE TITLE
Cannot build on windows

### ISSUE THREAD

**Issue by phisk** [antoyo/futures-glib-rs#10]
Hi there :)

Building on windows https://github.com/antoyo/relm/blob/master/examples/clock.rs fails with following error:

```
Compiling futures-glib v0.3.1
error[E0423]: expected value, found module `ptr`
  --> C:\Users\p\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-glib-0.3.1\src\io\mod.rs:41:18
   |
41 |         assert!(!ptr.is_null());
   |                  ^^^----------
   |                  |
   |                  did you mean `ptr::is_null(...)`?

error[E0423]: expected value, found module `ptr`
  --> C:\Users\p\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-glib-0.3.1\src\io\mod.rs:43:20
   |
43 |             inner: ptr,
   |                    ^^^ not a value

error: aborting due to 2 previous errors

error: Could not compile `futures-glib`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Building the same on linux works fine

**Comment by antoyo** [comment]
Thank you for reporting this issue.

Could you please try [this PR](https://github.com/antoyo/futures-glib-rs/pull/9)?
Just clone this repository and run `cargo test`, please.

I don't have Windows so I cannot test it.
AppVeyor seems to fail due to using an old Rust version.

**Comment by phisk** [comment]
output from win gnu stable:

`PS C:\Users\p\Documents\futures-glib-test\futures-glib-rs> cargo test
   Compiling winapi v0.2.8
   Compiling cfg-if v0.1.2
   Compiling byteorder v1.2.1
   Compiling log v0.3.8
   Compiling bitflags v1.0.1
   Compiling slab v0.3.0
   Compiling winapi-build v0.1.1
   Compiling gdk v0.7.0
   Compiling gdk-pixbuf v0.3.0
   Compiling gtk v0.3.0
   Compiling futures v0.1.17
   Compiling lazy_static v0.2.11
   Compiling cairo-rs v0.3.0
   Compiling gio v0.3.0
   Compiling libc v0.2.34
   Compiling pkg-config v0.3.9
   Compiling c_vec v1.2.1
   Compiling kernel32-sys v0.2.2
   Compiling ws2_32-sys v0.2.1
   Compiling gdk-pixbuf-sys v0.5.0
   Compiling cairo-sys-rs v0.5.0
   Compiling gio-sys v0.5.0
   Compiling gdk-sys v0.5.0
   Compiling gtk-sys v0.5.0
   Compiling pango-sys v0.5.0
   Compiling glib-sys v0.5.0
   Compiling atk-sys v0.5.0
   Compiling gobject-sys v0.5.0
   Compiling glib v0.4.0
   Compiling pango v0.3.0
   Compiling iovec v0.1.1
   Compiling net2 v0.2.31
   Compiling bytes v0.4.5
   Compiling tokio-io v0.1.4
   Compiling futures-glib v0.3.1 (file:///C:/Users/p/Documents/futures-glib-test/futures-glib-rs)
warning: unused import: `std::cell::RefCell`
 --> src\net\tcp.rs:1:5
  |
1 | use std::cell::RefCell;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `std::time::Duration`
 --> src\net\tcp.rs:6:5
  |
6 | use std::time::Duration;
  |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `glib_sys`
  --> src\net\tcp.rs:16:5
   |
16 | use glib_sys;
   |     ^^^^^^^^

warning: function is never used: `bits`
   --> src\io\mod.rs:315:1
    |
315 | pub fn bits(condition: &IoCondition) -> glib_sys::GIOCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default

warning: function is never used: `bits_new`
   --> src\io\mod.rs:319:1
    |
319 | pub fn bits_new(bits: glib_sys::GIOCondition) -> IoCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `std::cell::RefCell`
 --> src\net\tcp.rs:1:5
  |
1 | use std::cell::RefCell;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `std::time::Duration`
 --> src\net\tcp.rs:6:5
  |
6 | use std::time::Duration;
  |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `glib_sys`
  --> src\net\tcp.rs:16:5
   |
16 | use glib_sys;
   |     ^^^^^^^^

warning: function is never used: `bits`
   --> src\io\mod.rs:315:1
    |
315 | pub fn bits(condition: &IoCondition) -> glib_sys::GIOCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default

warning: function is never used: `bits_new`
   --> src\io\mod.rs:319:1
    |
319 | pub fn bits_new(bits: glib_sys::GIOCondition) -> IoCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Finished dev [unoptimized + debuginfo] target(s) in 80.92 secs
     Running target\debug\deps\futures_glib-28f170c1983ca324.exe

running 3 tests
test stack::tests::drain_drops ... ok
test stack::tests::drop_drops ... ok
test stack::tests::simple ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\context-55e73fa263fd3f77.exe

running 4 tests
test smoke ... ok
test locking ... ok
test thread_default ... ok
test wakeup ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\executor-18c5f829da6290e8.exe

running 6 tests
test oneshot ... ok
test smoke ... ok
test oneshot2 ... ok
test spawn_in_pol ... ok
test oneshot_many ... ok
test unpark_after_done ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\loop-45f6bcf17efe9156.exe

running 1 test
test smoke ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\source-ee2b4264de92eabd.exe

running 1 test
test smoke ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\tcp-a2272d67c4a0515e.exe

running 3 tests
test read_lots has been running for over 60 seconds
test smoke has been running for over 60 seconds
test write_lots has been running for over 60 seconds`

**Comment by phisk** [comment]
out put from win gnu nigthly:

`PS C:\Users\p\Documents\futures-glib-test\futures-glib-rs> rustup default  nightly-x86_64-pc-windows-gnu
info: using existing install for 'nightly-x86_64-pc-windows-gnu'
info: default toolchain set to 'nightly-x86_64-pc-windows-gnu'

  nightly-x86_64-pc-windows-gnu unchanged - rustc 1.24.0-nightly (bb42071f6 2017-12-01)

PS C:\Users\p\Documents\futures-glib-test\futures-glib-rs> cargo test
   Compiling futures-glib v0.3.1 (file:///C:/Users/p/Documents/futures-glib-test/futures-glib-rs)
warning: unused import: `std::cell::RefCell`
 --> src\net\tcp.rs:1:5
  |
1 | use std::cell::RefCell;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `std::time::Duration`
 --> src\net\tcp.rs:6:5
  |
6 | use std::time::Duration;
  |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `glib_sys`
  --> src\net\tcp.rs:16:5
   |
16 | use glib_sys;
   |     ^^^^^^^^

warning: unused import: `std::cell::RefCell`
 --> src\net\tcp.rs:1:5
  |
1 | use std::cell::RefCell;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `std::time::Duration`
 --> src\net\tcp.rs:6:5
  |
6 | use std::time::Duration;
  |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `glib_sys`
  --> src\net\tcp.rs:16:5
   |
16 | use glib_sys;
   |     ^^^^^^^^

warning: function is never used: `bits`
   --> src\io\mod.rs:315:1
    |
315 | pub fn bits(condition: &IoCondition) -> glib_sys::GIOCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default

warning: function is never used: `bits_new`
   --> src\io\mod.rs:319:1
    |
319 | pub fn bits_new(bits: glib_sys::GIOCondition) -> IoCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: function is never used: `bits`
   --> src\io\mod.rs:315:1
    |
315 | pub fn bits(condition: &IoCondition) -> glib_sys::GIOCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default

warning: function is never used: `bits_new`
   --> src\io\mod.rs:319:1
    |
319 | pub fn bits_new(bits: glib_sys::GIOCondition) -> IoCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Finished dev [unoptimized + debuginfo] target(s) in 6.55 secs
     Running target\debug\deps\futures_glib-940deca0f4d11b57.exe

running 3 tests
test stack::tests::drain_drops ... ok
test stack::tests::drop_drops ... ok
test stack::tests::simple ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\context-f5cd74402a729e23.exe

running 4 tests
test smoke ... ok
test thread_default ... ok
test wakeup ... ok
test locking ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\executor-cdab7242237f48a9.exe

running 6 tests
test smoke ... ok
test spawn_in_pol ... ok
test unpark_after_done ... ok
test oneshot ... ok
test oneshot2 ... ok
test oneshot_many ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\loop-548ee6be2ef0691f.exe

running 1 test
test smoke ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\source-118665b64952850c.exe

running 1 test
test smoke ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\tcp-88d5e782b7bf6663.exe

running 3 tests
test smoke has been running for over 60 seconds
test read_lots has been running for over 60 seconds
test write_lots has been running for over 60 seconds`

**Comment by phisk** [comment]
output from win gnu beta:

`PS C:\Users\p\Documents\futures-glib-test\futures-glib-rs> rustup default  beta-x86_64-pc-windows-gnu
info: using existing install for 'beta-x86_64-pc-windows-gnu'
info: default toolchain set to 'beta-x86_64-pc-windows-gnu'

  beta-x86_64-pc-windows-gnu unchanged - rustc 1.23.0-beta.1 (082b0ff02 2017-11-21)

PS C:\Users\p\Documents\futures-glib-test\futures-glib-rs> cargo test
   Compiling slab v0.3.0
   Compiling gdk v0.7.0
   Compiling bitflags v1.0.1
   Compiling gdk-pixbuf v0.3.0
   Compiling cfg-if v0.1.2
   Compiling futures v0.1.17
   Compiling winapi v0.2.8
   Compiling winapi-build v0.1.1
   Compiling gtk v0.3.0
   Compiling c_vec v1.2.1
   Compiling libc v0.2.34
   Compiling log v0.3.8
   Compiling cairo-rs v0.3.0
   Compiling byteorder v1.2.1
   Compiling pkg-config v0.3.9
   Compiling lazy_static v0.2.11
   Compiling gio v0.3.0
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.2
   Compiling cairo-sys-rs v0.5.0
   Compiling gtk-sys v0.5.0
   Compiling gio-sys v0.5.0
   Compiling pango-sys v0.5.0
   Compiling gdk-pixbuf-sys v0.5.0
   Compiling gobject-sys v0.5.0
   Compiling gdk-sys v0.5.0
   Compiling atk-sys v0.5.0
   Compiling glib-sys v0.5.0
   Compiling glib v0.4.0
   Compiling pango v0.3.0
   Compiling iovec v0.1.1
   Compiling net2 v0.2.31
   Compiling bytes v0.4.5
   Compiling tokio-io v0.1.4
   Compiling futures-glib v0.3.1 (file:///C:/Users/p/Documents/futures-glib-test/futures-glib-rs)
warning: unused import: `std::cell::RefCell`
 --> src\net\tcp.rs:1:5
  |
1 | use std::cell::RefCell;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `std::time::Duration`
 --> src\net\tcp.rs:6:5
  |
6 | use std::time::Duration;
  |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `glib_sys`
  --> src\net\tcp.rs:16:5
   |
16 | use glib_sys;
   |     ^^^^^^^^

warning: function is never used: `bits`
   --> src\io\mod.rs:315:1
    |
315 | pub fn bits(condition: &IoCondition) -> glib_sys::GIOCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default

warning: function is never used: `bits_new`
   --> src\io\mod.rs:319:1
    |
319 | pub fn bits_new(bits: glib_sys::GIOCondition) -> IoCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `std::cell::RefCell`
 --> src\net\tcp.rs:1:5
  |
1 | use std::cell::RefCell;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `std::time::Duration`
 --> src\net\tcp.rs:6:5
  |
6 | use std::time::Duration;
  |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `glib_sys`
  --> src\net\tcp.rs:16:5
   |
16 | use glib_sys;
   |     ^^^^^^^^

warning: function is never used: `bits`
   --> src\io\mod.rs:315:1
    |
315 | pub fn bits(condition: &IoCondition) -> glib_sys::GIOCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default

warning: function is never used: `bits_new`
   --> src\io\mod.rs:319:1
    |
319 | pub fn bits_new(bits: glib_sys::GIOCondition) -> IoCondition {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Finished dev [unoptimized + debuginfo] target(s) in 198.20 secs
     Running target\debug\deps\futures_glib-8a0504dcec49a0a6.exe

running 3 tests
test stack::tests::drain_drops ... ok
test stack::tests::drop_drops ... ok
test stack::tests::simple ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\context-c0825af0d39fa300.exe

running 4 tests
test smoke ... ok
test locking ... ok
test thread_default ... ok
test wakeup ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\executor-5970fa09e3cd74d7.exe

running 6 tests
test oneshot ... ok
test oneshot2 ... ok
test smoke ... ok
test spawn_in_pol ... ok
test oneshot_many ... ok
test unpark_after_done ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\loop-dd7d8d3be5c7469d.exe

running 1 test
test smoke ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\source-0bb0510b8a58215d.exe

running 1 test
test smoke ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\tcp-88dcf0894685a9fa.exe

running 3 tests
test smoke has been running for over 60 seconds
test read_lots has been running for over 60 seconds
test write_lots has been running for over 60 seconds`

**Comment by antoyo** [comment]
Thank you.
I merged that PR and published a new version.
